name: flutter_grpc_client
description: Flutter project showing how gRPC can be used in concert with a user-facing application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  grpc: ^4.0.1
  protobuf: ^3.1.0
  intl: ^0.18.0
  window_manager: ^0.5.0
  flutter_dotenv: ^5.1.0
  aws_secretsmanager_api: ^2.0.0
  aws_signature_v4: ^0.5.0
  http: ^1.1.0
  web: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  protoc_plugin: ^21.1.2

flutter:
  uses-material-design: true
  assets:
      - .env.dev